IMAGE logoBg "logo.png" NONE 1 
IMAGE logArc "logoarcade.png" NONE 1
IMAGE menu "menu.png" NONE 1
IMAGE lvl1 "map1.png" NONE 1
IMAGE lvl1_2 "level1-2.png" NONE 1
IMAGE lvl1_3 "level1-3.png" NONE 1
IMAGE lvl1_4 "level1-4.png" NONE 1
IMAGE fondo "fondo.png" NONE 1
IMAGE cueva1 "cueva1.png" NONE 1
IMAGE cueva2 "cueva2.png" NONE 1
IMAGE cueva3 "cueva3.png" NONE 1